version: '{build}'
image: Ubuntu2004
environment:
  global:
    HAXELIB_ROOT: /home/appveyor/haxelib
    HAXE_INSTALLDIR: /home/appveyor/haxe

install:
  - cd /home/appveyor
  - sudo add-apt-repository ppa:haxe/releases -y
  - sudo apt update
  - sudo apt install neko tar gcc-7 g++-7 gcc-7-multilib g++-7-multilib -y
  - wget https://github.com/HaxeFoundation/haxe/releases/download/4.2.3/haxe-4.2.3-linux64.tar.gz
  - mkdir $HAXE_INSTALLDIR
  - tar -xf haxe-4.2.3-linux64.tar.gz -C $HAXE_INSTALLDIR
  - export PATH=$PATH:$HAXE_INSTALLDIR/haxe_20201231082044_5e33a78aa
  - mkdir $HAXELIB_ROOT && haxelib setup $HAXELIB_ROOT
  - haxelib install lime 7.9.0
  - haxelib install openfl
  - haxelib git flixel https://github.com/TheRealJake12/flixel.git
  - haxelib run lime setup flixel
  - haxelib run lime setup
  - haxelib install flixel-tools
  - haxelib install flixel-addons
  - haxelib install flixel-ui
  - haxelib install hscript
  - haxelib install hxcpp-debug-server
  - haxelib git faxe https://github.com/uhrobots/faxe
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
  - haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
  - haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
  - haxelib install actuate
  - haxelib list
  - cd /home/appveyor/projects/kade-engine-community-linux

build_script:
  - haxelib run lime build linux

after_build:
  - tar -cvf KadeEngine-Linux.tar -C /home/appveyor/projects/kade-engine-community-linux/export/release/linux/bin .

artifacts:
- path: KadeEngineCommunity-Linux.tar
  name: Linux Build