
name: Linux Build
on:
  push:
jobs:
  build:
    name: Linux Build
    runs-on: ubuntu-22.04
    steps:
      - name: hxvlc bs wtf
        run: |
          sudo apt-get update
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          sudo apt-get install glibc-source
          sudo apt-get install libidn12
          sudo apt-get install libidn-dev
          
      - name: Pulling the source
        uses: actions/checkout@v4.1.6
      - name: Setting up Haxe
        uses: krdlab/setup-haxe@v1.5.1
        with:
          haxe-version: 4.3.4
      - name: Restore existing build cache for faster compilation
        uses: actions/cache@v4.0.2
        with:
          # not caching the bin folder to prevent asset duplication and stuff like that
          key: cache-build-linux
          path: |
            .haxelib/
            export/release/linux/haxe/
            export/release/linux/obj/
          restore-keys: |
            cache-build-linux
      - name: Installing/Updating libraries
        run: |
          haxe -cp ./update -D analyzer-optimize -main Update --interp
      - name: Building the game
        run: |
          haxelib run lime build linux
      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Kade Engine Community
          path: export/release/linux/bin
      - name: Clearing already existing cache
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-linux") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }
      - name: Uploading new cache
        uses: actions/cache@v4.0.2
        with:
          # caching again since for some reason it doesnt work with the first post cache shit
          key: cache-build-linux
          path: |
            .haxelib/
            export/release/linux/haxe/
            export/release/linux/obj/
          restore-keys: |
            cache-build-linux
